### ISSUE TITLE
/model/predict fails if the default option "--" is selected in the swagger UI 

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Image-Completer#7]
- Open swagger ui
- try endpoint
- choose image
- sect "default" option --

Result:

```
[2018-12-06 18:59:25,103] ERROR in app: Exception on /model/predict [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/workspace/api/model.py", line 101, in post
    image_path = self.model_wrapper.predict(input_data, image_mask_type)
  File "/workspace/core/backend.py", line 59, in predict
    dcgan.complete(args)
  File "/workspace/core/model_DCGAN.py", line 292, in complete
    assert(False)
AssertionError
172.17.0.1 - - [06/Dec/2018 18:59:25] "POST /model/predict HTTP/1.1" 500 -
```

**Comment by SSaishruthi** [comment]
By default, mask type is assigned to center. When the user gives '--'  option, default option is getting overwritten. Can resolve this issue in two ways.
1. Make input for mask_type mandatory similar to image type (only PNG/ JPG). Basically, mask type is required for completion.
2. Edit code to accept the default value.

**Comment by bdwyer2** [comment]
Is it possible to simply not provide `--` as a selection in the drop down list?

**Comment by ptitzler** [comment]
> Is it possible to simply not provide -- as a selection in the drop down list?
That'd make sense considering that the user wouldn't know what "--"  represents and what default (if any) is applied. 

> Edit code to accept the default value. It won't provide a desirable output.
Not sure what "desirable output" means.

**Comment by SSaishruthi** [comment]
Code has been updated to remove '--' and have only 4 mask options. Added details about default option in swagger.
